name: Continuous Deployment with Docker

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clonning Repository
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and push docker image
        with:
          image: u201711778/yatawaki-api
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
